FROM python:3.11-slim

WORKDIR /app

COPY requirements-frontend.txt .
RUN pip install --no-cache-dir -r requirements-frontend.txt

COPY frontend.py .

EXPOSE 8501

CMD ["streamlit", "run", "frontend.py", "--server.address", "0.0.0.0"]
