name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install les dépendances
        run: pip install -r requirements.txt pytest httpx

      - name: Run tests
        run: pytest tests/ -v

  docs:
    name: Deploy Docs
    runs-on: ubuntu-22.04
    needs: tests
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Param Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install mkdocs
        run: pip install mkdocs-material

      - name: Deploiement GitHub Pages
        run: mkdocs gh-deploy --force
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker:
    name: Build & Push Docker Images
    runs-on: ubuntu-22.04
    needs: tests
    steps:
      - uses: actions/checkout@v4

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build & push backend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.backend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iris-backend:latest

      - name: Build & push frontend
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.frontend
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/iris-frontend:latest
